app_id: 6L903538-42B1-4596-G479-BJ779F21A65C
publisher: wsurge
publisher_url: https://github.com/wsurge404/wsurge
display_name: wsurge
executable_name: wsurge.exe
output_base_file_name: wsurge.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\wsurge"
locales:
  - en
script_template: inno_setup.sas
